wget http://passets-ec.pinterest.com/webapp/style/app/common/images/502_tools-1x.25709c9c.png
wget http://passets-ec.pinterest.com/webapp/style/app/common/images/empty_followers-1x.de6dd7d1.png
wget http://passets-ec.pinterest.com/webapp/style/app/common/images/empty_following-1x.6ada63b4.png
wget http://passets-ec.pinterest.com/webapp/style/app/common/images/empty_robot-1x.bdeacb98.png
wget http://passets-ec.pinterest.com/webapp/style/app/common/images/empty_robot-2x.44168f8c.png
wget http://passets-ec.pinterest.com/webapp/style/app/common/images/empty_user_boards-1x.028e60ea.png
wget http://passets-ec.pinterest.com/webapp/style/app/common/images/empty_user_likes-1x.f7469980.png
wget http://passets-ec.pinterest.com/webapp/style/app/common/images/empty_user_pins-1x.71d0443a.png
wget http://passets-ec.pinterest.com/webapp/style/app/common/images/spinner-medium-1x.654fb1fe.gif
wget http://passets-ec.pinterest.com/webapp/style/app/common/images/spinner-medium-2x.ca5dc496.gif
wget http://passets-ec.pinterest.com/webapp/style/app/common/images/spinner-small-1x.a3a89185.gif
wget http://passets-ec.pinterest.com/webapp/style/app/common/images/spinner-small-2x.654fb1fe.gif
wget http://passets-ec.pinterest.com/webapp/style/app/common/images/spinner.0f376298.gif
wget http://passets-ec.pinterest.com/webapp/style/app/common/images/spinning_pin-1x.0aa9b7f6.gif
wget http://passets-ec.pinterest.com/webapp/style/app/common/images/spinning_pin-2x.a74938c4.gif
wget http://passets-ec.pinterest.com/webapp/style/app/common/images/white-spinner-medium-1x.60bd1c2b.gif
wget http://passets-ec.pinterest.com/webapp/style/app/common/images/white-spinner-medium-2x.21447508.gif
wget http://passets-ec.pinterest.com/webapp/style/app/common/images/white-spinner-small-1x.8a287dde.gif
wget http://passets-ec.pinterest.com/webapp/style/app/common/images/white-spinner-small-2x.60bd1c2b.gif
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/ClusterRed_ie-1x.d2793735.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/Cluster_ie-1x.1da81d8f.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/MarkerRed_ie-1x.37b83ce4.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/Marker_ie-1x.82eeb52b.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/add_pin_to_map_no_image-1x.5efb5162.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/add_pin_to_map_no_image-2x.dea04f36.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/boardPinsGridShadowBottom.bbcac9fc.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/boardPinsGridShadowTop.232a2e57.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/board_search_helper-1x.c5793cbf.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/board_search_helper-2x.cdf23d29.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/compass-1x.96cec4cd.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/compass-2x.f55f809d.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/confirm-bg-1x.f007652c.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/confirm-bg-2x.09867747.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/convert_to_biz-1x.5b2d08e4.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/convert_to_biz-2x.733faffb.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/default_30_30-1x.318d32d5.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/empty_find_friends_facebook_logo-1x.9f00b312.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/empty_find_friends_twitter_logo-1x.b36d7a53.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/empty_following_feed_tile_bg.a5ad6192.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/example_pin-1x.0dcac5e4.jpg
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/example_pin-2x.5c19f98c.jpg
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/extension_graphic-1x.f3a8ed4a.jpg
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/extension_graphic-2x.2057ca17.jpg
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/follow-friends-checkmark-1x.9839b8ee.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/friend-center-null-state-asset-1x.46f10236.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/friend-center-null-state-asset-2x.fde4e2e9.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/get_pinterest_mobile.9ecf1913.jpg
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/hero_japan-1x.a4720875.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/hero_japan-2x.9990b583.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/hero_language-1x.e2adf00a.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/hero_language-2x.34dd1eed.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/hero_places_layer_1.ae3b5b2b.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/hero_places_layer_2.c2dd60e0.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/hero_places_layer_3.6bb4d8b5.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/hero_places_layer_4a.1fb3083c.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/hero_places_layer_4b.6785ae15.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/hero_places_layer_5.dbb5e1c7.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/hero_places_layer_6.0de128a2.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/hero_places_layer_7.2682c08f.jpg
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/hero_promote_a_pin-1x.3a23980b.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/hero_promote_a_pin-2x.c2ba4492.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/hero_scooter_pinner_story_bg.df5b5f47.jpg
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/icon-edit-1x.de226b8a.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/ignition/ignition1-1x.09c5a309.gif
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/ignition/ignition2-1x.6e7fa711.gif
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/ignition/ignition3-1x.a0db9c7f.gif
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/infoBarActiveShadowLeftSide.9195d28e.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/install_app-1x.85eed42f.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/install_app-2x.f4640307.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/invite-landing-banner-1x.1e97a275.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/invite-landing-banner-2x.afd94863.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/inviter-helper-1x.31a4e04a.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/layers-1x.5b2ef6e3.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/logged_out_splash.626d1d51.jpg
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/map_board_page_translucent_bg-1x.042f7c91.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/pin-invite-mail-1x.5cc8a444.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/pin-invite-mail-2x.4075094a.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/pin-it-web-1x.3a2bfaae.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/pin-it-web-2x.a15a7a81.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/pin-shadow-1x.081fffa9.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/pin-shadow-2x.d56324c9.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/pin-source-1x.96ad4975.jpg
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/pin-source-2x.42ea6a96.jpg
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/pin-usage-1x.e64c7ad7.jpg
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/pin-usage-2x.64be051a.jpg
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/pin_create_success_extension_nag_win_chrome.3fd98b07.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/sample_pin-1x.35c1f69c.jpg
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/sample_pin-2x.a730e453.jpg
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/social_network_separator.bd2ce808.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/tutorial_empty_pins.7567d16c.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/unauth_home_empty_feed_hero.5c445294.png
wget http://passets-ec.pinterest.com/webapp/style/app/desktop/images/x_map_grid_bg.53887af8.png
wget http://passets-ec.pinterest.com/webapp/style/sprites/webapp-common-emojis-1x.88609db3.png
wget http://passets-ec.pinterest.com/webapp/style/sprites/webapp-common-main-1x.790cb90a.png
wget http://passets-ec.pinterest.com/webapp/style/sprites/webapp-common-main-2x.c5b93997.png
wget http://passets-ec.pinterest.com/webapp/style/sprites/webapp-desktop-flags-1x.f32102e0.png
wget http://passets-ec.pinterest.com/webapp/style/sprites/webapp-desktop-flags-2x.f03f1283.png
wget http://passets-ec.pinterest.com/webapp/style/sprites/webapp-desktop-main-1x.0b14ae60.png
wget http://passets-ec.pinterest.com/webapp/style/sprites/webapp-desktop-main-2x.85d73a0e.png
wget http://passets-ec.pinterest.com/webapp/style/sprites/webapp-desktop-unauth-1x.174dcf5d.png
wget http://passets-ec.pinterest.com/webapp/style/sprites/webapp-desktop-unauth-2x.8890df57.png
